services:
  app:
    build: 
      context: .
    image: myapp:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://akshat:password@db:5432/mydatabase
      NODE_ENV: development
    depends_on:
      - db
    develop:
      watch :
        - action : sync
          path : ./src
          target : /app/src
          ignore : ['**/node_modules/**', '**/dist/**']
        - action : rebuild
          path : ./package.json
          target : /app/package.json
          ignore : ['**/node_modules/**', '**/dist/**']

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: akshat
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"