version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: finsight-postgres
    environment:
      POSTGRES_USER: finsight
      POSTGRES_PASSWORD: finsight
      POSTGRES_DB: finsight
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: finsight-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
